sudo: required
services:
    -   docker

before_install:
    -   docker build -t benconnekt/react-with-docker -f Dockerfile.dev .

script:
    -   docker run -e CI=true benconnekt/react-with-docker npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "eu-west-2"
    app: "react-with-docker"
    env: "ReactWithDocker-env"
    bucket_name: "elasticbeanstalk-eu-west-2-135800214573"
    bucket_path: "react-with-docker"
    on:
        branch: master

language: generic