sudo: required
services:
    -   docker

before_install:
    -   docker build -t benconnekt/react-with-docker -f Dockerfile.dev .

script:
    -   docker run -e CI=true benconnekt/react-with-docker npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "ReactWithDocker"
    env: "ReactWithDocker-env"
    bucket_name: "elasticbeanstalk-eu-west-2-135800214573"
    bucket_path: "ReactWithDocker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY


language: generic

ReactWithDocker-env.eba-k6frh3k5.eu-west-2.elasticbeanstalk.com 
