sudo: required
services:
    -   docker

before_install:
    -   docker build -t benconnekt/react-with-docker -f Dockerfile.dev .

script:
    -   docker run -e CI=true benconnekt/react-with-docker npm run test -- --coverage

language: generic
